chore
PiperOrigin-RevId: 840347591

diff --git a/.github/actions/version-check/action.yml b/.github/actions/version-check/action.yml
--- a/.github/actions/version-check/action.yml
+++ b/.github/actions/version-check/action.yml
@@ -5,7 +5,12 @@ inputs:
   python_version:
     description: The Python version of the build toolchain to use.
     required: true
-    default: 3.11
+  semver_prefix:
+    description: The prefix of the package version.
+    required: true
+  current_version:
+    description: The current package version.
+    required: true
 
 outputs:
   new_version:
@@ -19,18 +24,27 @@ runs:
       with:
         fetch-depth: 0  # Important: fetch all tags for comparison
         fetch-tags: true
-    - uses: ./.github/actions/install-meridian
-      with:
-        python_version: ${{ inputs.python_version }}
-        extras: ''
     - shell: bash
       run: pip install semver
     - id: version_check
       name: Check Version
       shell: bash
-      # This relies on the git repository having "v{major}.{minor}.{patch}" named tags.
+      # This relies on the git repository having "{prefix}{major}.{minor}.{patch}" named tags.
       run: |
-        CURRENT_VERSION=$(python3 -c "import meridian; print(meridian.__version__)")
+        CURRENT_VERSION=${{ inputs.current_version }}
+        PREVIOUS_TAG=$(git describe --tags --abbrev=0 --match '${{ inputs.semver_prefix }}*' || { echo "Error: No matching previous tag found." >&2; exit 1; })
+        PREVIOUS_VERSION=$(echo "$PREVIOUS_TAG" | sed 's/^${{ inputs.semver_prefix }}//')
+
+        echo "CURRENT_VERSION: $CURRENT_VERSION"
+        echo "PREVIOUS_TAG: $PREVIOUS_TAG"
+        echo "PREVIOUS_VERSION: $PREVIOUS_VERSION"
+
+        # Check if first version
+        if [ -z "$PREVIOUS_TAG" ]; then
+          echo "Warning: No matching previous tag found with pattern '${{ inputs.semver_prefix }}*'. Assuming first version."
+          echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
+          exit 0
+        fi
 
         # Validate CURRENT_VERSION using semver check
         if ! python3 -m semver check "$CURRENT_VERSION"; then
@@ -38,17 +52,10 @@ runs:
           exit 1 # Fail fast
         fi
 
-        PREVIOUS_TAG=$(git describe --tags --abbrev=0 --match 'v*' || { echo "Error: No matching previous tag found." >&2; exit 1; })
-        PREVIOUS_VERSION=$(echo "$PREVIOUS_TAG" | sed 's/^v//')
-
-        echo "CURRENT_VERSION: $CURRENT_VERSION"
-        echo "PREVIOUS_TAG: $PREVIOUS_TAG"
-        echo "PREVIOUS_VERSION: $PREVIOUS_VERSION"
-
         if [[ $(python3 -m semver compare "$CURRENT_VERSION" "$PREVIOUS_VERSION") -eq 1 ]]; then
           echo "New version detected: $CURRENT_VERSION"
-          NEW_VERSION=$CURRENT_VERSION
+          echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
         else
           echo "No version increment detected."
+          echo "new_version=" >> $GITHUB_OUTPUT
         fi
-        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
