fix
PiperOrigin-RevId: 831471160

diff --git a/.github/workflows/proto-publish.yml b/.github/workflows/proto-publish.yml
--- a/.github/workflows/proto-publish.yml
+++ b/.github/workflows/proto-publish.yml
@@ -41,18 +41,52 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-
-      - name: Read package version from pyproject.toml
-        uses: SebRollen/toml-action@v1.2.0
-        id: read_toml
         with:
-          file: pyproject.toml
-          field: 'project.version'
+          fetch-depth: 0  # Important: fetch all tags for comparison
+          fetch-tags: true
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ env.USE_PYTHON_VERSION }}
+
+      - name: Install semver
+        shell: bash
+        run: pip install semver
+
+      - name: Get version
+        id: get_version
+        shell: bash
+        run: |
+          VERSION=$(python -c """
+          import sys
+          import tomllib
+
+          try:
+            filepath = '${{ env.PROTO_DIR }}/pyproject.toml'
+            with open(filepath, 'rb') as f:
+              data = tomllib.load(f)
+
+            version = data.get('project', {}).get('version', '')
+            if version:
+              print(version)
+            else:
+              print(f"Error: Version not found in {filepath} under [project.version]")
+              sys.exit(1)
+          except FileNotFoundError:
+            print(f"Error: File {filepath} not found", file=sys.stderr)
+            sys.exit(1)
+          """
+          if [ $? -ne 0 ]; then
+            echo "Failed to get version from ${{ env.PROTO_DIR}}/pyproject.toml"
+            exit 1
+          fi
+          echo "value=$VERSION" >> $GITHUB_OUTPUT
 
       - name: Compare versions
         id: compare_versions
         run: |
-          CURRENT_VERSION = "${{ steps.read_toml.outputs.value }}"
+          CURRENT_VERSION="${{ steps.get_version.outputs.value }}"
           PREVIOUS_TAG=$(git describe --tags --abbrev=0 --match 'v*' || { echo "Error: No matching previous tag found." >&2; exit 1; })
           PREVIOUS_VERSION=$(echo "$PREVIOUS_TAG" | sed 's/^v//')
 
