Trigger `publish-to-pypi` job when `check-version.outputs.new_version` is not empty
PiperOrigin-RevId: 721902917

diff --git a/.github/workflows/pytest_and_autopublish.yml b/.github/workflows/pytest_and_autopublish.yml
--- a/.github/workflows/pytest_and_autopublish.yml
+++ b/.github/workflows/pytest_and_autopublish.yml
@@ -116,17 +116,55 @@ jobs:
         fi
         echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
 
+  create-tag:
+    name: Create Version Tag
+    runs-on: ubuntu-latest
+    needs: check-version
+    if: ${{ needs.check-version.outputs.new_version != '' }} # Only run if new_version was discovered.
+    steps:
+      - uses: actions/checkout@v4
+      - name: Create and Push Tag
+        uses: actions/github-script@v6
+        with:
+          script: |
+            const newTag = 'v${{ needs.check-version.outputs.new_version }}';
+            try {
+              await github.rest.git.createTag({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                tag: newTag,
+                message: `Release ${newTag}`,
+                object: context.sha,
+                type: 'commit'
+              });
+              await github.rest.git.createRef({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                ref: `refs/tags/${newTag}`,
+                sha: context.sha
+              });
+              console.log(`Created and pushed new tag: ${newTag}`);
+            } catch (error) {
+              console.error('Error creating tag:', error);
+              core.setFailed(`Failed to create tag: ${error.message}`);
+            }
+
   publish-to-pypi:
-    name: >-
-      Publish Python distribution to PyPI
-    # Check if it's a tag push or the `publish_to_pypi` workflow is selected in a manual trigger.
-    if: >
-      (github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/'))
-      || (github.event_name == 'workflow_dispatch'
-          && github.event.inputs.publish_to_pypi == 'true')
+    name: Publish Python distribution to PyPI
     needs:
     - build
     - pytest-job
+    - check-version
+    # Check if it's a tag push or the `publish_to_pypi` workflow is selected in a manual trigger,
+    # or if a new version was detected--but only for the `main` branch.
+    if: >
+      github.ref == 'refs/heads/main'
+      && (
+        (github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/'))
+        || (github.event_name == 'workflow_dispatch'
+            && github.event.inputs.publish_to_pypi == 'true')
+        || needs.check-version.outputs.new_version != ''
+      )
     runs-on: ubuntu-latest
     environment:
       name: pypi
